# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170131_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_place', to='api.Place'),
        ),
    ]
